osx build

diff --git a/contrib/build-osx/make_osx b/contrib/build-osx/make_osx
--- a/contrib/build-osx/make_osx
+++ b/contrib/build-osx/make_osx
@@ -26,7 +26,7 @@ fail "Unable to use Python $PYTHON_VERSION"
 
 if ! which pyinstaller > /dev/null; then
   info "Installing pyinstaller"
-  python3 -m pip install pyinstaller -I --user || fail "Could not install pyinstaller"
+  python3 -m pip install pyinstaller==3.6 -I --user || fail "Could not install pyinstaller"
 fi
 
 info "Using these versions for building Electrum:"
@@ -69,14 +69,14 @@ python3 -m pip install pyqt5 --user || \
 fail "Could not install requirements"
 
 info "Compile images..."
-pyrcc5 -no-compress icons.qrc -o electrum/gui/qt/icons_rc.py || fail "pyrcc5 not found"
+~/Library/Python/3.6/bin/pyrcc5 icons.qrc -o electrum/gui/qt/icons_rc.py || fail "pyrcc5 not found"
 
 info "Installing hardware wallet requirements..."
 python3 -m pip install -Ir ./contrib/deterministic-build/requirements-hw.txt --user || \
 fail "Could not install hardware wallet requirements"
 
 info "Building Electrum..."
-python3 setup.py install > /dev/null || fail "Could not build Electrum"
+python3 setup.py install --user > /dev/null || fail "Could not build Electrum"
 
 info "Building binary"
 pyinstaller --noconfirm --ascii --name $VERSION contrib/build-osx/osx.spec || fail "Could not build binary"
